name: Owen Potts
favicon: null
layout_spectrum: 0.6536509017460048
typography_spectrum: 0.23590520699508488
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7990184128284454
  lightness: 0.3979886448942125
  saturation: 0.506514630978927
  rhythmicContrast: 0.38993479451164603
purpose: []
