name: Owen Potts
favicon: null
layout_spectrum: 0.6536509017460048
typography_spectrum: 0.23590520699508488
title: 'Hypnotherapist, Clairvoyant, Medium'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
