name: Owen Potts
favicon: null
layout_spectrum: 0.51636
typography_spectrum: 0.42329
title: 'Hypnotherapist, Clairvoyant, Medium'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ecf8f6'
    - '#a5b39c'
    - '#978b73'
    - '#7d5744'
    - '#491600'
  brandStrength: 0.875
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
